version: '2'
services:

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password!
      MYSQL_DATABASE: scheduler
      MYSQL_USER: scheduler
      MYSQL_PASSWORD: Cgp75iXX
      MYSQL_HOST: ""
    volumes:
      - ./dbdata:/var/lib/mysql

  master:
    image: kunitaya/jobscheduler
    hostname: master
    environment:
      MYSQL_DATABASE: scheduler
      MYSQL_USER: scheduler
      MYSQL_PASSWORD: Cgp75iXX
      MYSQL_HOST: db
      MYSQL_PORT: 3306
    ports:
      - "4444:4444"
      - "40444:40444"
    depends_on:
      - db
    volumes:
      - ./jobdata:/var/local/scheduler/scheduler/config/live
      - ./logs:/var/log/sos-berlin.com/jobscheduler/scheduler

  joc:
    image: kunitaya/joccockpit
    hostname: cockpit
    environment:
      MYSQL_DATABASE: scheduler
      MYSQL_USER: scheduler
      MYSQL_PASSWORD: Cgp75iXX
      MYSQL_HOST: db
      MYSQL_PORT: 3306
    ports:
      - "4446:4446"
      - "40446:40446"
    depends_on:
      - db
